# Analysis options for resx library
# This file configures the static analysis results for your project.

include: package:lints/recommended.yaml

linter:
  rules:
    # Style
    - camel_case_types
    - camel_case_extensions
    - file_names
    - non_constant_identifier_names
    - constant_identifier_names
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    
    # Design
    - use_super_parameters
    - unnecessary_constructor_name
    - unnecessary_late
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    
    # Performance
    - prefer_collection_literals
    - prefer_spread_collections
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    
    # Error prone
    - avoid_empty_else
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  language:
    strict-casts: true
    strict-raw-types: true
