name: resx
description: "Functional error handling for Dart: Result/Option/Validation + AsyncResult, Stream/Iterable utils, and tiny state Loadable."
version: 0.4.1
repository: https://github.com/fluttercandies/resx
homepage: https://github.com/fluttercandies/resx
documentation: https://pub.dev/documentation/resx/latest/
issue_tracker: https://github.com/fluttercandies/resx/issues

environment:
  sdk: ^3.3.0

topics:
  - result
  - option
  - validation
  - functional-programming
  - error-handling

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

funding:
  - https://github.com/sponsors/iota9star
